feat: use build time defined Device Type instead of hardcoded
mendersoftware/mender-mcu-integration pull request #12
Opened 2024-09-30 11:55 UTC by larsewi

Ticket: MEN-7547
Changelog: Title
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

2024-10-01 07:21 UTC, lluiscampos requested changes
I am missing one thing:

:point_right:  To set `CONFIG_MENDER_DEVICE_TYPE` in the project properties. Here we have a golden opportunity to set it per board, using the `boards/...conf` files

> Merge together with [mendersoftware/mender-mcu#85](https://github.com/mendersoftware/mender-mcu/pull/85)

Not really. We first need to merge `mender-mcu`, then port it to the stable branch there, and only then we can merge this PR in `mender-mcu-integration`

2024-10-01 07:50 UTC, vpodzime commented on src/main.c
> -#define DEVICE_TYPE   "espressif-esp32"
Let's please have a reasonable default. I think it should be `CONFIG_BOARD_TARGET`.

2024-10-01 07:51 UTC, vpodzime approved these changes
ACK

2024-10-02 15:13 UTC, larsewi commented
> I am missing one thing:
>
> 👉 To set CONFIG_MENDER_DEVICE_TYPE in the project properties. Here we have a golden opportunity to set it per board, using the boards/...conf files

Maybe I'm misunderstanding you. But currently `CONFIG_MENDER_DEVICE_TYPE` is set automatically based on Zephyrs `CONFIG_BOARD_TARGET`. Below is contents in `west build -t menuconfig` after a pristine build:

![Screenshot 2024-10-02 at 16 44 31](https://github.com/user-attachments/assets/4ca3ec4c-4d29-497f-8f6d-d3dcadaae078)

2024-10-03 07:52 UTC, lluiscampos approved these changes
> @lluiscampos maybe I'm misunderstanding you. But currently `CONFIG_MENDER_DEVICE_TYPE` is set automatically based on Zephyrs `CONFIG_BOARD_TARGET`. Below is contents in `west build -t menuconfig` after a pristine build:

Yes, I completely misunderstood the implementation on my first review. Sorry for the noise. It is fine as-is. Just don't merge it before we get the feature merged into stable branch v0.2 in `mender-mcu`.

2024-10-04 09:27 UTC, merged